const GET_TRANSACTIONS = {
  GET_TRANSACTIONS: {
    GET: 'GET_TRANSACTIONS',
    OPTION_DATE: 'UPDATE_OPTION_DATE',
    FILTER: 'SET_FILTER',
    SET_LOADING_TRANSACTIONS: 'SET_LOADING_TRANSACTIONS',
    TOTAL_SALES: 'SET_TOTAL_SALES',
  }
}

export default GET_TRANSACTIONS;